title: awesome-learning
lang: en
description: Extends the continuous integration documentation capabilities of GitHub pages for everyone!

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

markdown: kramdown # For mathetical formula
kramdown:
    input: GFM

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
