title: awesome-learning
lang: en
description: Extends the continuous integration documentation capabilities of GitHub pages for everyone!

# remote_themeï¼šrundocs/jekyll-rtd-theme
# remote_theme: clearpathrobotics/jekyll-rtd-theme # Or
remote_theme: https://github.com/clearpathrobotics/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
